version: '3'
services:
  keycloak:
    build: ./oidc-idp-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - frontend 
      - backend
  openidc-auth-proxy:
    build: ./oidc-proxy
    ports:
     - "80:80"
    networks:
      - frontend 
      - backend
  app1:
    build: ./oidc-backend
    ports:
      - "8090"
    environment:
      - SERVER_PORT=8090
      - SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://keycloak:8080/auth/realms/myapp/protocol/openid-connect/certs
      - SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8080/auth/realms/myapp
    networks: 
      - backend

networks:
  frontend:  
  backend: