version: "3"
services:
  keycloak:
    build: ./oidc-idp-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
  openidc-auth-proxy:
    build: ./oidc-proxy
    ports:
      - "80:80"
  backend:
    build: ./oidc-backend
    ports:
      - "8090"
    environment:
      - SERVER_PORT=8090
      - SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://keycloak:8080/realms/myapp/protocol/openid-connect/certs
      - SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8080/realms/myapp
  frontend:
    build: ./oidc-frontend
    ports:
      - "80"
